package com.mycompany.catl;

import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paean Luby 
 * @author Nicolás Rodríguez Sánchez 
 */
public class DistributedProgrammingGUI extends javax.swing.JFrame {

    private RemoteInterface madridRi;
    private RemoteInterface barcelonaRi;

    /**
     * Creates new form DistributedProgrammingGUI
     */
    public DistributedProgrammingGUI() {
        initComponents();
        try {
            madridRi = (RemoteInterface) Naming.lookup("//localhost/madrid");
            barcelonaRi = (RemoteInterface) Naming.lookup("//localhost/barcelona");
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        buttonMadridCloseRunway1 = new javax.swing.JButton();
        buttonMadridOpenRunway1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        buttonMadridCloseRunway2 = new javax.swing.JButton();
        buttonMadridOpenRunway2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonMadridCloseRunway3 = new javax.swing.JButton();
        buttonMadridCloseRunway4 = new javax.swing.JButton();
        buttonMadridOpenRunway4 = new javax.swing.JButton();
        buttonMadridOpenRunway3 = new javax.swing.JButton();
        madridHangar = new javax.swing.JTextField();
        madridParking = new javax.swing.JTextField();
        madridPassengers = new javax.swing.JTextField();
        madridTaxiArea = new javax.swing.JTextField();
        madridMaintenance = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        barcelonaPassengers = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        barcelonaHangar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        barcelonaMaintenance = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        barcelonaParking = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        barcelonaTaxiArea = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        buttonBarcelonaCloseRunway1 = new javax.swing.JButton();
        buttonBarcelonaOpenRunway1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        buttonBarcelonaCloseRunway3 = new javax.swing.JButton();
        buttonBarcelonaOpenRunway3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        buttonBarcelonaCloseRunway2 = new javax.swing.JButton();
        buttonBarcelonaOpenRunway2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        buttonBarcelonaCloseRunway4 = new javax.swing.JButton();
        buttonBarcelonaOpenRunway4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        AirwayMadridBarcelona = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        AirwayBarcelonaMadrid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Madrid Airport");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Barcelona Airport");

        jLabel3.setText("Number of passengers at the Airport:");

        jLabel4.setText("Number of passengers in Hangar:");

        jLabel5.setText("Number of passengers in Maintenance:");

        jLabel6.setText("Number of passengers in Parking:");

        jLabel7.setText("Number of passengers in Taxi Area:");

        jLabel8.setText("Runway 1");

        buttonMadridCloseRunway1.setText("Close");
        buttonMadridCloseRunway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridCloseRunway1ActionPerformed(evt);
            }
        });

        buttonMadridOpenRunway1.setText("Open");
        buttonMadridOpenRunway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridOpenRunway1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Runway 2");

        buttonMadridCloseRunway2.setText("Close");
        buttonMadridCloseRunway2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridCloseRunway2ActionPerformed(evt);
            }
        });

        buttonMadridOpenRunway2.setText("Open");
        buttonMadridOpenRunway2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridOpenRunway2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Runway 4");

        jLabel11.setText("Runway 3");

        buttonMadridCloseRunway3.setText("Close");
        buttonMadridCloseRunway3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridCloseRunway3ActionPerformed(evt);
            }
        });

        buttonMadridCloseRunway4.setText("Close");
        buttonMadridCloseRunway4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridCloseRunway4ActionPerformed(evt);
            }
        });

        buttonMadridOpenRunway4.setText("Open");
        buttonMadridOpenRunway4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridOpenRunway4ActionPerformed(evt);
            }
        });

        buttonMadridOpenRunway3.setText("Open");
        buttonMadridOpenRunway3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMadridOpenRunway3ActionPerformed(evt);
            }
        });

        madridHangar.setEditable(false);
        madridHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridHangarActionPerformed(evt);
            }
        });

        madridParking.setEditable(false);
        madridParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridParkingActionPerformed(evt);
            }
        });

        madridPassengers.setEditable(false);
        madridPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridPassengersActionPerformed(evt);
            }
        });

        madridTaxiArea.setEditable(false);
        madridTaxiArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridTaxiAreaActionPerformed(evt);
            }
        });

        madridMaintenance.setEditable(false);
        madridMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridMaintenanceActionPerformed(evt);
            }
        });

        jLabel12.setText("Number of passengers at the Airport:");

        barcelonaPassengers.setEditable(false);
        barcelonaPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaPassengersActionPerformed(evt);
            }
        });

        jLabel13.setText("Number of passengers in Hangar:");

        barcelonaHangar.setEditable(false);
        barcelonaHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaHangarActionPerformed(evt);
            }
        });

        jLabel14.setText("Number of passengers in Maintenance:");

        barcelonaMaintenance.setEditable(false);
        barcelonaMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaMaintenanceActionPerformed(evt);
            }
        });

        jLabel15.setText("Number of passengers in Parking:");

        barcelonaParking.setEditable(false);
        barcelonaParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaParkingActionPerformed(evt);
            }
        });

        jLabel16.setText("Number of passengers in Taxi Area:");

        barcelonaTaxiArea.setEditable(false);
        barcelonaTaxiArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaTaxiAreaActionPerformed(evt);
            }
        });

        jLabel17.setText("Runway 1");

        buttonBarcelonaCloseRunway1.setText("Close");
        buttonBarcelonaCloseRunway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaCloseRunway1ActionPerformed(evt);
            }
        });

        buttonBarcelonaOpenRunway1.setText("Open");
        buttonBarcelonaOpenRunway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaOpenRunway1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Runway 3");

        buttonBarcelonaCloseRunway3.setText("Close");
        buttonBarcelonaCloseRunway3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaCloseRunway3ActionPerformed(evt);
            }
        });

        buttonBarcelonaOpenRunway3.setText("Open");
        buttonBarcelonaOpenRunway3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaOpenRunway3ActionPerformed(evt);
            }
        });

        jLabel19.setText("Runway 2");

        buttonBarcelonaCloseRunway2.setText("Close");
        buttonBarcelonaCloseRunway2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaCloseRunway2ActionPerformed(evt);
            }
        });

        buttonBarcelonaOpenRunway2.setText("Open");
        buttonBarcelonaOpenRunway2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaOpenRunway2ActionPerformed(evt);
            }
        });

        jLabel20.setText("Runway 4");

        buttonBarcelonaCloseRunway4.setText("Close");
        buttonBarcelonaCloseRunway4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaCloseRunway4ActionPerformed(evt);
            }
        });

        buttonBarcelonaOpenRunway4.setText("Open");
        buttonBarcelonaOpenRunway4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBarcelonaOpenRunway4ActionPerformed(evt);
            }
        });

        jLabel21.setText("Airway Madrid-Barcelona");

        AirwayMadridBarcelona.setEditable(false);
        AirwayMadridBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirwayMadridBarcelonaActionPerformed(evt);
            }
        });

        jLabel22.setText("Airway Barcelona-Madrid");

        AirwayBarcelonaMadrid.setEditable(false);
        AirwayBarcelonaMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirwayBarcelonaMadridActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(madridTaxiArea))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridCloseRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridOpenRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridCloseRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridOpenRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridCloseRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridOpenRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridCloseRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonMadridOpenRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(madridParking))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(madridPassengers))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(madridMaintenance))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(madridHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barcelonaTaxiArea))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaCloseRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaOpenRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaCloseRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaOpenRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaCloseRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaOpenRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaCloseRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonBarcelonaOpenRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(barcelonaParking))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(barcelonaPassengers))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(barcelonaMaintenance))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(barcelonaHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AirwayMadridBarcelona)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AirwayBarcelonaMadrid)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel22)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(madridPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(madridHangar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(madridMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(barcelonaPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(barcelonaHangar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(barcelonaMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(madridParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(madridTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(buttonMadridCloseRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMadridOpenRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(buttonMadridCloseRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMadridOpenRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(buttonMadridCloseRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMadridOpenRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(buttonMadridCloseRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonMadridOpenRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(barcelonaParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(barcelonaTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(buttonBarcelonaCloseRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBarcelonaOpenRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(buttonBarcelonaCloseRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBarcelonaOpenRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(buttonBarcelonaCloseRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBarcelonaOpenRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(buttonBarcelonaCloseRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonBarcelonaOpenRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AirwayMadridBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AirwayBarcelonaMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMadridCloseRunway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridCloseRunway1ActionPerformed
        try {
            madridRi.openClose(0, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridCloseRunway1ActionPerformed

    private void buttonMadridOpenRunway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridOpenRunway1ActionPerformed
        try {
            madridRi.openClose(0, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridOpenRunway1ActionPerformed

    private void buttonMadridCloseRunway2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridCloseRunway2ActionPerformed
        try {
            madridRi.openClose(1, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridCloseRunway2ActionPerformed

    private void buttonMadridOpenRunway2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridOpenRunway2ActionPerformed
        try {
            madridRi.openClose(1, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridOpenRunway2ActionPerformed

    private void buttonMadridCloseRunway3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridCloseRunway3ActionPerformed
        try {
            madridRi.openClose(2, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridCloseRunway3ActionPerformed

    private void buttonMadridCloseRunway4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridCloseRunway4ActionPerformed
        try {
            madridRi.openClose(3, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridCloseRunway4ActionPerformed

    private void buttonMadridOpenRunway4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridOpenRunway4ActionPerformed
        try {
            madridRi.openClose(3, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridOpenRunway4ActionPerformed

    private void buttonMadridOpenRunway3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMadridOpenRunway3ActionPerformed
        try {
            madridRi.openClose(2, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonMadridOpenRunway3ActionPerformed

    private void madridHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridHangarActionPerformed

    private void madridParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridParkingActionPerformed

    private void madridPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridPassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridPassengersActionPerformed

    private void madridTaxiAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridTaxiAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridTaxiAreaActionPerformed

    private void madridMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridMaintenanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridMaintenanceActionPerformed

    private void barcelonaPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaPassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaPassengersActionPerformed

    private void barcelonaHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaHangarActionPerformed

    private void barcelonaMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaMaintenanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaMaintenanceActionPerformed

    private void barcelonaParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaParkingActionPerformed

    private void barcelonaTaxiAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaTaxiAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaTaxiAreaActionPerformed

    private void buttonBarcelonaCloseRunway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaCloseRunway1ActionPerformed
        try {
            barcelonaRi.openClose(0, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaCloseRunway1ActionPerformed

    private void buttonBarcelonaOpenRunway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaOpenRunway1ActionPerformed
        try {
            barcelonaRi.openClose(0, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaOpenRunway1ActionPerformed

    private void buttonBarcelonaCloseRunway3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaCloseRunway3ActionPerformed
        try {
            barcelonaRi.openClose(2, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaCloseRunway3ActionPerformed

    private void buttonBarcelonaOpenRunway3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaOpenRunway3ActionPerformed
        try {
            barcelonaRi.openClose(2, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaOpenRunway3ActionPerformed

    private void buttonBarcelonaCloseRunway2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaCloseRunway2ActionPerformed
        try {
            barcelonaRi.openClose(1, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaCloseRunway2ActionPerformed

    private void buttonBarcelonaOpenRunway2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaOpenRunway2ActionPerformed
        try {
            barcelonaRi.openClose(1, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaOpenRunway2ActionPerformed

    private void buttonBarcelonaCloseRunway4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaCloseRunway4ActionPerformed
        try {
            barcelonaRi.openClose(3, false);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaCloseRunway4ActionPerformed

    private void buttonBarcelonaOpenRunway4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBarcelonaOpenRunway4ActionPerformed
        try {
            barcelonaRi.openClose(3, true);
        } catch (RemoteException ex) {
            Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonBarcelonaOpenRunway4ActionPerformed

    private void AirwayMadridBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirwayMadridBarcelonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirwayMadridBarcelonaActionPerformed

    private void AirwayBarcelonaMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirwayBarcelonaMadridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirwayBarcelonaMadridActionPerformed

    public void setMadridHangar(int hangar) {
        this.madridHangar.setText(Integer.toString(hangar));
    }

    public void setMadridPassengers(AtomicInteger passengers) {
        this.madridPassengers.setText(passengers.toString());
    }

    public void setMadridMaintenance(int passengers) {
        this.madridMaintenance.setText(Integer.toString(passengers));
    }

    public void setMadridParking(int passengers) {
        this.madridParking.setText(Integer.toString(passengers));
    }

    public void setMadridTaxiArea(int passengers) {
        this.madridTaxiArea.setText(Integer.toString(passengers));
    }

    public void setAirwayMadridBarcelona(String arway) {
        this.AirwayMadridBarcelona.setText(arway);
    }

    public void setBarcelonaHangar(int hangar) {
        this.barcelonaHangar.setText(Integer.toString(hangar));
    }

    public void setBarcelonaPassengers(AtomicInteger passengers) {
        this.barcelonaPassengers.setText(passengers.toString());
    }

    public void setBarcelonaMaintenance(int passengers) {
        this.barcelonaMaintenance.setText(Integer.toString(passengers));
    }

    public void setBarcelonaParking(int passengers) {
        this.barcelonaParking.setText(Integer.toString(passengers));
    }

    public void setBarcelonaTaxiArea(int passengers) {
        this.barcelonaTaxiArea.setText(Integer.toString(passengers));
    }

    public void setAirwayBarcelonaMadrid(String arway) {
        this.AirwayBarcelonaMadrid.setText(arway);
    }

    public void set() throws RemoteException {
        while (true) {
            setMadridHangar(madridRi.numHangar());
            setMadridPassengers(madridRi.getPassengers());
            setMadridMaintenance(madridRi.numMaintenance());
            setMadridParking(madridRi.numParking());
            setMadridTaxiArea(madridRi.numTaxiArea());
            setBarcelonaHangar(barcelonaRi.numHangar());
            setBarcelonaPassengers(barcelonaRi.getPassengers());
            setBarcelonaMaintenance(barcelonaRi.numMaintenance());
            setBarcelonaParking(barcelonaRi.numParking());
            setBarcelonaTaxiArea(barcelonaRi.numTaxiArea());
            setAirwayMadridBarcelona(madridRi.showMadBarAirway());
            setAirwayBarcelonaMadrid(madridRi.showBarMadAirway());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws NotBoundException, MalformedURLException, RemoteException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributedProgrammingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        RemoteInterface rI = (RemoteInterface) Naming.lookup("//localhost/");
//        while(true){
//            setMadridHangar(rI.numHangar());
//        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributedProgrammingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirwayBarcelonaMadrid;
    private javax.swing.JTextField AirwayMadridBarcelona;
    private javax.swing.JTextField barcelonaHangar;
    private javax.swing.JTextField barcelonaMaintenance;
    private javax.swing.JTextField barcelonaParking;
    private javax.swing.JTextField barcelonaPassengers;
    private javax.swing.JTextField barcelonaTaxiArea;
    private javax.swing.JButton buttonBarcelonaCloseRunway1;
    private javax.swing.JButton buttonBarcelonaCloseRunway2;
    private javax.swing.JButton buttonBarcelonaCloseRunway3;
    private javax.swing.JButton buttonBarcelonaCloseRunway4;
    private javax.swing.JButton buttonBarcelonaOpenRunway1;
    private javax.swing.JButton buttonBarcelonaOpenRunway2;
    private javax.swing.JButton buttonBarcelonaOpenRunway3;
    private javax.swing.JButton buttonBarcelonaOpenRunway4;
    private javax.swing.JButton buttonMadridCloseRunway1;
    private javax.swing.JButton buttonMadridCloseRunway2;
    private javax.swing.JButton buttonMadridCloseRunway3;
    private javax.swing.JButton buttonMadridCloseRunway4;
    private javax.swing.JButton buttonMadridOpenRunway1;
    private javax.swing.JButton buttonMadridOpenRunway2;
    private javax.swing.JButton buttonMadridOpenRunway3;
    private javax.swing.JButton buttonMadridOpenRunway4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField madridHangar;
    private javax.swing.JTextField madridMaintenance;
    private javax.swing.JTextField madridParking;
    private javax.swing.JTextField madridPassengers;
    private javax.swing.JTextField madridTaxiArea;
    // End of variables declaration//GEN-END:variables
}
