/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.catl;

import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

/**
 *
 * @author THINKPAD
 */
public class GraphicalInterface extends javax.swing.JFrame {

    /**
     * Creates new form GraphicalInterface
     */
    public GraphicalInterface() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pauseButton = new javax.swing.JButton();
        resumeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        madridMaintenance = new javax.swing.JTextField();
        madridHangar = new javax.swing.JTextField();
        madridParking = new javax.swing.JTextField();
        madridGate1 = new javax.swing.JTextField();
        madridGate4 = new javax.swing.JTextField();
        madridGate2 = new javax.swing.JTextField();
        madridGate5 = new javax.swing.JTextField();
        madridGate3 = new javax.swing.JTextField();
        madridGate6 = new javax.swing.JTextField();
        madridTaxiArea = new javax.swing.JTextField();
        madridRunway1 = new javax.swing.JTextField();
        madridRunway2 = new javax.swing.JTextField();
        madridRunway3 = new javax.swing.JTextField();
        madridRunway4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        madridBusTownAirport = new javax.swing.JTextField();
        madridBusAirportTown = new javax.swing.JTextField();
        madridPassengers = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        barcelonaBusTownAirport = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        barcelonaBusAirportTown = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        barcelonaPassengers = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        barcelonaHangar = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        barcelonaMaintenance = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        barcelonaParking = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        barcelonaGate1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        barcelonaGate2 = new javax.swing.JTextField();
        barcelonaGate4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        barcelonaGate5 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        barcelonaGate6 = new javax.swing.JTextField();
        barcelonaGate3 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        barcelonaTaxiArea = new javax.swing.JTextField();
        barcelonaRunway1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        barcelonaRunway2 = new javax.swing.JTextField();
        barcelonaRunway4 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        barcelonaRunway3 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        airwayMadridBarcelona = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        airwayBarcelonaMadrid = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Madrid Airport");

        pauseButton.setText("Pause");
        pauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseButtonActionPerformed(evt);
            }
        });

        resumeButton.setText("Resume");
        resumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Hangar:");

        jLabel4.setText("Maintenance: ");

        jLabel5.setText("Parking Area:");

        jLabel6.setText("Gate 1:");

        jLabel7.setText("Gate 2:");

        jLabel8.setText("Gate 3:");

        jLabel9.setText("Gate 5:");

        jLabel10.setText("Gate 4:");

        jLabel11.setText("Gate 6:");

        jLabel12.setText("Taxi area:");

        jLabel13.setText("Runway 2:");

        jLabel14.setText("Runway 1:");

        jLabel15.setText("Runway 3:");

        jLabel16.setText("Runway 4:");

        jLabel31.setText("Number of passengers at the airport:");

        jLabel32.setText("Transfers Downtown:");

        jLabel33.setText("Transfers Airport:");

        madridMaintenance.setEditable(false);
        madridMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        madridMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridMaintenanceActionPerformed(evt);
            }
        });

        madridHangar.setEditable(false);
        madridHangar.setBackground(new java.awt.Color(255, 255, 255));
        madridHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridHangarActionPerformed(evt);
            }
        });

        madridParking.setEditable(false);
        madridParking.setBackground(new java.awt.Color(255, 255, 255));
        madridParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridParkingActionPerformed(evt);
            }
        });

        madridGate1.setEditable(false);
        madridGate1.setBackground(new java.awt.Color(255, 255, 255));

        madridGate4.setEditable(false);
        madridGate4.setBackground(new java.awt.Color(255, 255, 255));

        madridGate2.setEditable(false);
        madridGate2.setBackground(new java.awt.Color(255, 255, 255));

        madridGate5.setEditable(false);
        madridGate5.setBackground(new java.awt.Color(255, 255, 255));

        madridGate3.setEditable(false);
        madridGate3.setBackground(new java.awt.Color(255, 255, 255));

        madridGate6.setEditable(false);
        madridGate6.setBackground(new java.awt.Color(255, 255, 255));

        madridTaxiArea.setEditable(false);
        madridTaxiArea.setBackground(new java.awt.Color(255, 255, 255));

        madridRunway1.setEditable(false);
        madridRunway1.setBackground(new java.awt.Color(255, 255, 255));

        madridRunway2.setEditable(false);
        madridRunway2.setBackground(new java.awt.Color(255, 255, 255));

        madridRunway3.setEditable(false);
        madridRunway3.setBackground(new java.awt.Color(255, 255, 255));

        madridRunway4.setEditable(false);
        madridRunway4.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        madridBusTownAirport.setEditable(false);
        madridBusTownAirport.setBackground(new java.awt.Color(255, 255, 255));
        madridBusTownAirport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridBusTownAirportActionPerformed(evt);
            }
        });

        madridBusAirportTown.setEditable(false);
        madridBusAirportTown.setBackground(new java.awt.Color(255, 255, 255));

        madridPassengers.setEditable(false);
        madridPassengers.setBackground(new java.awt.Color(255, 255, 255));
        madridPassengers.setText("0");
        madridPassengers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridPassengersActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel34.setText("Barcelona Airport");

        jLabel35.setText("Transfers Airport:");

        barcelonaBusTownAirport.setEditable(false);
        barcelonaBusTownAirport.setBackground(new java.awt.Color(255, 255, 255));

        jLabel36.setText("Transfers Downtown:");

        barcelonaBusAirportTown.setEditable(false);
        barcelonaBusAirportTown.setBackground(new java.awt.Color(255, 255, 255));
        barcelonaBusAirportTown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaBusAirportTownActionPerformed(evt);
            }
        });

        jLabel37.setText("Number of passengers at the airport:");

        barcelonaPassengers.setEditable(false);
        barcelonaPassengers.setBackground(new java.awt.Color(255, 255, 255));
        barcelonaPassengers.setText("0");

        jLabel38.setText("Hangar:");

        barcelonaHangar.setEditable(false);
        barcelonaHangar.setBackground(new java.awt.Color(255, 255, 255));
        barcelonaHangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaHangarActionPerformed(evt);
            }
        });

        jLabel39.setText("Maintenance: ");

        barcelonaMaintenance.setEditable(false);
        barcelonaMaintenance.setBackground(new java.awt.Color(255, 255, 255));
        barcelonaMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaMaintenanceActionPerformed(evt);
            }
        });

        jLabel40.setText("Parking Area:");

        barcelonaParking.setEditable(false);
        barcelonaParking.setBackground(new java.awt.Color(255, 255, 255));
        barcelonaParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaParkingActionPerformed(evt);
            }
        });

        jLabel41.setText("Gate 1:");

        barcelonaGate1.setEditable(false);
        barcelonaGate1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel42.setText("Gate 2:");

        barcelonaGate2.setEditable(false);
        barcelonaGate2.setBackground(new java.awt.Color(255, 255, 255));

        barcelonaGate4.setEditable(false);
        barcelonaGate4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel43.setText("Gate 4:");

        jLabel44.setText("Gate 5:");

        barcelonaGate5.setEditable(false);
        barcelonaGate5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel45.setText("Gate 6:");

        barcelonaGate6.setEditable(false);
        barcelonaGate6.setBackground(new java.awt.Color(255, 255, 255));

        barcelonaGate3.setEditable(false);
        barcelonaGate3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel46.setText("Gate 3:");

        jLabel47.setText("Taxi area");

        barcelonaTaxiArea.setEditable(false);
        barcelonaTaxiArea.setBackground(new java.awt.Color(255, 255, 255));

        barcelonaRunway1.setEditable(false);
        barcelonaRunway1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel48.setText("Runway 1");

        jLabel49.setText("Runway 2:");

        barcelonaRunway2.setEditable(false);
        barcelonaRunway2.setBackground(new java.awt.Color(255, 255, 255));

        barcelonaRunway4.setEditable(false);
        barcelonaRunway4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel50.setText("Runway 4:");

        jLabel51.setText("Runway 3:");

        barcelonaRunway3.setEditable(false);
        barcelonaRunway3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel52.setText("Airway Madrid-Barcelona:");

        airwayMadridBarcelona.setEditable(false);
        airwayMadridBarcelona.setBackground(new java.awt.Color(255, 255, 255));

        jLabel53.setText("Airway Barcelona-Madrid:");

        airwayBarcelonaMadrid.setEditable(false);
        airwayBarcelonaMadrid.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(airwayBarcelonaMadrid, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(airwayMadridBarcelona, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridGate2))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel8)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridGate3))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridGate1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridRunway1))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel16)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(madridRunway4))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel15)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(madridRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel10)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(madridGate4))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel9)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(madridGate5))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jLabel11)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(madridGate6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel33)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(madridBusTownAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel32)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(madridBusAirportTown, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel31)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(madridPassengers))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(madridHangar))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(madridMaintenance))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(101, 101, 101)
                                                    .addComponent(jLabel1))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridParking, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel12)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(madridTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addGap(16, 16, 16)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel34))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaBusTownAirport, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel36)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaBusAirportTown, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaPassengers))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaHangar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaMaintenance))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaParking)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel49)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel50)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(barcelonaRunway4))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel51)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(barcelonaRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(barcelonaTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel42)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel46)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel41)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel45)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel44)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate5))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel43)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(barcelonaGate4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(0, 308, Short.MAX_VALUE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(jLabel52)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel53)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(pauseButton)
                .addGap(25, 25, 25)
                .addComponent(resumeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pauseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resumeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(barcelonaBusTownAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barcelonaBusAirportTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(barcelonaPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barcelonaHangar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(barcelonaMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(barcelonaParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel41)
                                    .addComponent(barcelonaGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel42)
                                    .addComponent(barcelonaGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel46)
                                    .addComponent(barcelonaGate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(barcelonaGate4)
                                    .addComponent(jLabel43))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44)
                                    .addComponent(barcelonaGate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45)
                                    .addComponent(barcelonaGate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(barcelonaTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel51)
                                    .addComponent(barcelonaRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barcelonaRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49)
                                    .addComponent(jLabel50)
                                    .addComponent(barcelonaRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(barcelonaRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel47)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(madridBusTownAirport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridBusAirportTown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(madridPassengers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(madridHangar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(madridMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(madridParking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(madridGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridGate4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(madridGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridGate5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(madridGate3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridGate6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(madridTaxiArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(madridRunway1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridRunway3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(madridRunway2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(madridRunway4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airwayMadridBarcelona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(airwayBarcelonaMadrid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void madridParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridParkingActionPerformed

    private void madridHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridHangarActionPerformed

    private void madridMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridMaintenanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridMaintenanceActionPerformed

    private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumeButtonActionPerformed
        if (!resumePressed) //If not pressed
        {
            resumePressed = true;             //we change it to pulsed
            pausePressed = false;
            gw.open();    //Close the gateway for paiters
        }
    }//GEN-LAST:event_resumeButtonActionPerformed

    private void pauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseButtonActionPerformed
        if (!pausePressed) //If not pressed
        {
            resumePressed = false;             //we change it to pulsed
            pausePressed = true;
            gw.close();    //Close the gateway for paiters
        }
    }//GEN-LAST:event_pauseButtonActionPerformed

    private void barcelonaHangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaHangarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaHangarActionPerformed

    private void barcelonaMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaMaintenanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaMaintenanceActionPerformed

    private void barcelonaParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaParkingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaParkingActionPerformed

    private void madridPassengersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridPassengersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridPassengersActionPerformed

    private void madridBusTownAirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridBusTownAirportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_madridBusTownAirportActionPerformed

    private void barcelonaBusAirportTownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaBusAirportTownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcelonaBusAirportTownActionPerformed

    //All set methods for the graphical interface avoiding mutual exclusion when necessary
    private Lock lockMadridPassengers = new ReentrantLock();
    private Lock lockBarcelonaPassengers = new ReentrantLock();
    private Lock lockMadridBusTownAirport = new ReentrantLock();
    private Lock lockBarcelonaBusTownAirport = new ReentrantLock();
    private Lock lockMadridBusAirportTown = new ReentrantLock();
    private Lock lockBarcelonaBusAirportTown = new ReentrantLock();
    private Lock lockMadridHangar = new ReentrantLock();
    private Lock lockBarcelonaHangar = new ReentrantLock();
    private Lock lockMadridParking = new ReentrantLock();
    private Lock lockBarcelonaParking = new ReentrantLock();
    private Lock lockMadridTaxiArea = new ReentrantLock();
    private Lock lockBarcelonaTaxiArea = new ReentrantLock();
    private Lock lockAirwayMadridBarcelona = new ReentrantLock();
    private Lock lockAirwayBarcelonaMadrid = new ReentrantLock();
    private Lock lockMadridMaintenanceHall = new ReentrantLock();
    private Lock lockBarcelonaMaintenanceHall = new ReentrantLock();
    private Gateway gw = new Gateway();
    private boolean resumePressed = false;
    private boolean pausePressed = false;

    public Gateway getGw() {
        return gw;
    }

    public void setMadridPassengers(AtomicInteger madridPassengers) {
        lockMadridPassengers.lock();
        try {
            this.madridPassengers.setText(String.valueOf(madridPassengers));
        } catch (Exception e) {
        } finally {
            lockMadridPassengers.unlock();
        }
    }

    public void setBarcelonaPassengers(AtomicInteger barcelonaPassengers) {
        lockBarcelonaPassengers.lock();
        try {
            this.barcelonaPassengers.setText(String.valueOf(barcelonaPassengers));
        } catch (Exception e) {
        } finally {
            lockBarcelonaPassengers.unlock();
        }
    }

    public void setMadridBusTownAirport(String bus) {
        lockMadridBusTownAirport.lock();
        try {
            this.madridBusTownAirport.setText(bus);
        } catch (Exception e) {
        } finally {
            lockMadridBusTownAirport.unlock();
        }
    }

    public void setBarcelonaBusTownAirport(String bus) {
        lockBarcelonaBusTownAirport.lock();
        try {
            this.barcelonaBusTownAirport.setText(bus);
        } catch (Exception e) {
        } finally {
            lockBarcelonaBusTownAirport.unlock();
        }
    }

    public void setMadridBusAirportTown(String bus) {
        lockMadridBusAirportTown.lock();
        try {
            this.madridBusAirportTown.setText(bus);
        } catch (Exception e) {
        } finally {
            lockMadridBusAirportTown.unlock();
        }
    }

    public void setBarcelonaBusAirportTown(String bus) {
        lockBarcelonaBusAirportTown.lock();
        try {
            this.barcelonaBusAirportTown.setText(bus);
        } catch (Exception e) {
        } finally {
            lockBarcelonaBusAirportTown.unlock();
        }
    }

    public void setMadridHangar(String hangar) {
        lockMadridHangar.lock();
        try {
            this.madridHangar.setText(hangar);
        } catch (Exception e) {
        } finally {
            lockMadridHangar.unlock();
        }
    }

    public void setBarcelonaHangar(String hangar) {
        lockBarcelonaHangar.lock();
        try {
            this.barcelonaHangar.setText(hangar);
        } catch (Exception e) {
            // Aquí podrías manejar la excepción si lo deseas
        } finally {
            lockBarcelonaHangar.unlock();
        }
    }

    public void setMadridParking(String parking) {
        lockMadridParking.lock();
        try {
            this.madridParking.setText(parking);
        } catch (Exception e) {
            // Aquí podrías manejar la excepción si lo deseas
        } finally {
            lockMadridParking.unlock();
        }
    }

    public void setBarcelonaParking(String parking) {
        lockBarcelonaParking.lock();
        try {
            this.barcelonaParking.setText(parking);
        } catch (Exception e) {
            // Aquí podrías manejar la excepción si lo deseas
        } finally {
            lockBarcelonaParking.unlock();
        }
    }

    public void setMadridGate1(String gate) {
        this.madridGate1.setText(gate);
    }

    public void setMadridGate2(String gate) {
        this.madridGate2.setText(gate);
    }

    public void setMadridGate3(String gate) {
        this.madridGate3.setText(gate);
    }

    public void setMadridGate4(String gate) {
        this.madridGate4.setText(gate);
    }

    public void setMadridGate5(String gate) {
        this.madridGate5.setText(gate);
    }

    public void setMadridGate6(String gate) {
        this.madridGate6.setText(gate);
    }

    public void setBarcelonaGate1(String gate) {
        this.barcelonaGate1.setText(gate);
    }

    public void setBarcelonaGate2(String gate) {
        this.barcelonaGate2.setText(gate);
    }

    public void setBarcelonaGate3(String gate) {
        this.barcelonaGate3.setText(gate);
    }

    public void setBarcelonaGate4(String gate) {
        this.barcelonaGate4.setText(gate);
    }

    public void setBarcelonaGate5(String gate) {
        this.barcelonaGate5.setText(gate);
    }

    public void setBarcelonaGate6(String gate) {
        this.barcelonaGate6.setText(gate);
    }

    public void setMadridTaxiArea(String taxiArea) {
        lockMadridTaxiArea.lock();
        try {
            this.madridTaxiArea.setText(taxiArea);
        } catch (Exception e) {
        } finally {
            lockMadridTaxiArea.unlock();
        }
    }

    public void setMadridRunway1(String runway) {
        this.madridRunway1.setText(runway);
    }

    public void setMadridRunway2(String runway) {
        this.madridRunway2.setText(runway);
    }

    public void setMadridRunway3(String runway) {
        this.madridRunway3.setText(runway);
    }

    public void setMadridRunway4(String runway) {
        this.madridRunway4.setText(runway);
    }

    public void setBarcelonaTaxiArea(String taxiArea) {
        lockBarcelonaTaxiArea.lock();
        try {
            this.barcelonaTaxiArea.setText(taxiArea);
        } catch (Exception e) {
        } finally {
            lockBarcelonaTaxiArea.unlock();
        }
    }

    public void setBarcelonaRunway1(String runway) {
        this.barcelonaRunway1.setText(runway);
    }

    public void setBarcelonaRunway2(String runway) {
        this.barcelonaRunway2.setText(runway);
    }

    public void setBarcelonaRunway3(String runway) {
        this.barcelonaRunway3.setText(runway);
    }

    public void setBarcelonaRunway4(String runway) {
        this.barcelonaRunway4.setText(runway);
    }

    public void setAirwayMadridBarcelona(String airway) {
        lockAirwayMadridBarcelona.lock();
        try {
            this.airwayMadridBarcelona.setText(airway);
        } catch (Exception e) {
        } finally {
            lockAirwayMadridBarcelona.unlock();
        }
    }

    public void setAirwayBarcelonaMadrid(String airway) {
        lockAirwayBarcelonaMadrid.lock();
        try {
            this.airwayBarcelonaMadrid.setText(airway);
        } catch (Exception e) {
        } finally {
            lockAirwayBarcelonaMadrid.unlock();
        }
    }

    public void setMadridMaintenanceHall(String maintenanceHall) {
        lockMadridMaintenanceHall.lock();
        try {
            this.madridMaintenance.setText(maintenanceHall);
        } catch (Exception e) {
        } finally {
            lockMadridMaintenanceHall.unlock();
        }
    }

    public void setBarcelonaMaintenanceHall(String maintenanceHall) {
        lockBarcelonaMaintenanceHall.lock();
        try {
            this.barcelonaMaintenance.setText(maintenanceHall);
        } catch (Exception e) {
        } finally {
            lockBarcelonaMaintenanceHall.unlock();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airwayBarcelonaMadrid;
    private javax.swing.JTextField airwayMadridBarcelona;
    private javax.swing.JTextField barcelonaBusAirportTown;
    private javax.swing.JTextField barcelonaBusTownAirport;
    private javax.swing.JTextField barcelonaGate1;
    private javax.swing.JTextField barcelonaGate2;
    private javax.swing.JTextField barcelonaGate3;
    private javax.swing.JTextField barcelonaGate4;
    private javax.swing.JTextField barcelonaGate5;
    private javax.swing.JTextField barcelonaGate6;
    private javax.swing.JTextField barcelonaHangar;
    private javax.swing.JTextField barcelonaMaintenance;
    private javax.swing.JTextField barcelonaParking;
    private javax.swing.JTextField barcelonaPassengers;
    private javax.swing.JTextField barcelonaRunway1;
    private javax.swing.JTextField barcelonaRunway2;
    private javax.swing.JTextField barcelonaRunway3;
    private javax.swing.JTextField barcelonaRunway4;
    private javax.swing.JTextField barcelonaTaxiArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField madridBusAirportTown;
    private javax.swing.JTextField madridBusTownAirport;
    private javax.swing.JTextField madridGate1;
    private javax.swing.JTextField madridGate2;
    private javax.swing.JTextField madridGate3;
    private javax.swing.JTextField madridGate4;
    private javax.swing.JTextField madridGate5;
    private javax.swing.JTextField madridGate6;
    private javax.swing.JTextField madridHangar;
    private javax.swing.JTextField madridMaintenance;
    private javax.swing.JTextField madridParking;
    private javax.swing.JTextField madridPassengers;
    private javax.swing.JTextField madridRunway1;
    private javax.swing.JTextField madridRunway2;
    private javax.swing.JTextField madridRunway3;
    private javax.swing.JTextField madridRunway4;
    private javax.swing.JTextField madridTaxiArea;
    private javax.swing.JButton pauseButton;
    private javax.swing.JButton resumeButton;
    // End of variables declaration//GEN-END:variables
}
